# Generated by Django 6.0.4 on 2026-05-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('anio_graduacion', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corporacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donador_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_ap', models.CharField(max_length=100)),
                ('segundo_ap', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Donador',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('primer_ap', models.CharField(max_length=100)),
                ('segundo_ap', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('anio_graduacion', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_conyuge', models.CharField(max_length=201)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.clase')),
                ('id_corporacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_corporacion', to='colectas.corporacion')),
                ('id_corporacion_conyuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_corporacion_conyuge', to='colectas.corporacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.donador_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.donador')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('numero_pagos', models.PositiveIntegerField(default=0)),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('id_circulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.circulo')),
                ('id_donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.donador')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.garantia')),
            ],
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('respuesta', models.CharField(max_length=50)),
                ('observaciones', models.TextField(max_length=1000)),
                ('id_donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.donador')),
                ('id_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.garantia')),
                ('id_voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.voluntario')),
            ],
        ),
    ]
