# Generated by Django 6.0.4 on 2026-05-31 04:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('anio_graduacion', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corporacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donador_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_ap', models.CharField(max_length=100)),
                ('segundo_ap', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Userio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('rol', models.CharField(default='usuario', max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Donador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_ap', models.CharField(max_length=100)),
                ('segundo_ap', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('anio_graduacion', models.PositiveSmallIntegerField(unique=True)),
                ('nombre_conyuge', models.CharField(max_length=201)),
                ('id_clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, to='colectas.clase')),
                ('id_corporacion', models.ForeignKey(db_column='id_corporacion', on_delete=django.db.models.deletion.CASCADE, related_name='id_corporacion', to='colectas.corporacion')),
                ('id_corporacion_conyuge', models.ForeignKey(db_column='id_corporacion_conyuge', on_delete=django.db.models.deletion.CASCADE, related_name='id_corporacion_conyuge', to='colectas.corporacion')),
                ('categoria', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='id_categoria', to='colectas.donador_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='check_fecha_fin')],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.donador')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('numero_pagos', models.PositiveIntegerField(default=0)),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('id_circulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.circulo')),
                ('id_donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.donador')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.garantia')),
            ],
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('respuesta', models.CharField(max_length=50)),
                ('observaciones', models.TextField(max_length=1000)),
                ('id_donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.donador')),
                ('id_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.garantia')),
                ('id_voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colectas.voluntario')),
            ],
        ),
    ]
