# Generated by Django 6.0.4 on 2026-05-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colectas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='userio',
            name='rol',
            field=models.CharField(default='usuario', max_length=255),
        ),
    ]
