# Generated by Django 6.0.4 on 2026-05-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colectas', '0002_delete_usuario_alter_userio_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='check_fecha_fin'),
        ),
    ]
