# Generated by Django 6.0.4 on 2026-05-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colectas', '0003_alter_evento_fecha_fin_alter_evento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evento',
            name='check_fecha_fin',
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='check_fecha_fin'),
        ),
    ]
